// ⚠️  This file is auto-generated by the Supabase CLI.
//    Do not edit it manually — your changes will be overwritten.
//
//    To regenerate, run from the repo root:
//      pnpm generate:types
//
//    Requires SUPABASE_PROJECT_ID to be set in your environment.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
